# Generated by Django 3.1 on 2020-08-27 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200827_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 16, 1, 0, 464488), verbose_name='Время написания'),
        ),
    ]
