# Generated by Django 3.1 on 2020-08-27 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200827_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 16, 8, 15, 953866), verbose_name='Время написания'),
        ),
    ]
