# Generated by Django 3.1 on 2020-08-27 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200827_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique_for_date='published_date'),
            preserve_default=False,
        ),
    ]
