# Generated by Django 3.1 on 2020-08-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='media/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
